export function uuid(): string;
export function documentHeight(): number;
export function isElement(obj: object): boolean;
export function isNumber(n: any): boolean;
export function isFloat(n: any): boolean;
export function prefixed(unprefixed: string): string;
export function defaults(obj: object, ...args: any[]): object;
export function extend(target: object, ...args: any[]): object;
export function locationOf(item: any, array: any, compareFunction?: Function, start?: Function, end?: Function): number;
export function insert(item: any, array: any, compareFunction?: Function): number;
export function indexOfSorted(item: any, array: any, compareFunction?: Function, start?: Function, end?: Function): number;
export function bounds(el: Element): {
    height: number;
    width: number;
};
export function borders(el: Element): {
    height: number;
    width: number;
};
export function nodeBounds(node: Node): DOMRect;
export function windowBounds(): {
    width: number;
    height: number;
    top: number;
    left: number;
    right: number;
    bottom: number;
};
export function indexOfNode(node: Node, typeId: string): number;
export function indexOfTextNode(textNode: Node): number;
export function indexOfElementNode(elementNode: Element): number;
export function isXml(ext: string): boolean;
export function createBlob(content: any, mime: string): Blob;
export function createBlobUrl(content: any, mime: string): string;
export function revokeBlobUrl(url: string): void;
export function createBase64Url(content: any, mime: string): string;
export function type(obj: object): string;
export function parse(markup: string, mime: string): Document;
export function qs(el: Element, sel: string): Element;
export function qsa(el: Element, sel: string): Element[];
export function qsp(el: Element, sel: string, props: object[]): Element[];
export function sprint(root: Element, func: Function): void;
export function treeWalker(root: Element, func: Function, filter: Function | object): void;
export function walk(node: Node, callback: Function): boolean;
export function blob2base64(blob: Blob): Promise<string>;
export function querySelectorByType(html: Element, element: string, type: string): Element[];
export function findChildren(el: Element): Element[];
export function parents(node: Node): Node[];
export function filterChildren(el: Element, nodeName: string, single?: boolean): Element[];
export function getParentByTagName(node: Node, tagname: string): Node[];
